#!/bin/bash

#SBATCH --job-name="DES_OTUPick_082017" #name of the job submitted

#SBATCH -p medium #name of the queue you are submitting to

#SBATCH -N 1 #number of nodes in this job

#SBATCH -n 20 #number of cores/tasks in job

#SBATCH -t 48:00:00 #time allocated for job in hrs:min:sec

#SBATCH --mail-user=djeppschmidt@gmail.com #email to get messages

#SBATCH --mail-type=BEGIN,END,FAIL #send mail when job starts, ends or fails

#SBATCH -o "DES_OTUpick082017_stdout.%j.%N" #standard out %j adds job number, %N adds node name

#SBATCH -e "DES_OTUpick082017_stderr.%j.%N" #optional file for standard error

#SBATCH --workdir=/project/microbial_genomes/php_output/bacteria/ #set the working directory
date # optional prints timestamp in stdout when job starts

module load qiime

pick_open_reference_otus.py -i /project/microbial_genomes/php_output/bacteria/OTU_pick_nochimera072817/filter_Chimeras/all_bact_no_ref_chimeras.fna -f -o /project/microbial_genomes/php_output/bacteria/OTU_pick_nochimera072817/OTU_Pick082017 -a -O 20

date #optional prints timestamp when the job ends to standard out

#End of file
